### ISSUE TITLE
$( document ).ready()

### ISSUE THREAD

**Issue by CWSites** [laurentvd/wavesurfer.swf#4]
After a few days of troubleshooting I found out that the JS does not load properly if you wrap it inside of `$( document ).ready()`, you must use `(function() {` or you're going to have a hard time getting this to work. 

Does anyone know why this is an issue?

**Comment by laurentvd** [comment]
Sorry to hear you're having trouble getting it to work. Can you elaborate on what's not working properly? Do you get a JS error or is something is going wrong? I don't see why jQuery's `$(document).ready()` would influence how it works, so if possible, could you show a codepen / jsbin / whatever showing the error?

**Comment by CWSites** [comment]
I think it's a conflict with some of our other code, I just noticed that it was failing silently when this was happening.

**Comment by sonnywang** [comment]
did anyone test in IE11? it did not work

**Comment by laurentvd** [comment]
@sonnywang Can you be more specific? What doesn't work? Do you see errors in the console?

**Comment by laurentvd** [comment]
I'm closing this for now. Please feel free to reopen it if needed.
