### ISSUE TITLE
forced naming convention for HTML container?

### ISSUE THREAD

**Issue by jbeyer05** [laurentvd/wavesurfer.swf#5]
It would seem that the HTML container for a wave surfer element must be named 'wavesurfer'.  The non-Flash version of wavesurfer does not have this requirement.
If my understanding is indeed correct that the element must be name 'wavesurfer', I would suggest mentioning this in the documentation.  I was trying to port an application that used the non-Flash version previously, and it took me some time to figure out this requirement.

**Comment by laurentvd** [comment]
Thanks for mentioning this. It actually is not forced, you can pass it as a parameter when creating the WaveSurfer.Swf instance. For example

```
var waveSurfer = new WaveSurfer.Swf('myCustomId');
```

It is omitted in the demo code though, and that probably is a bad idea ;-) I'll change that to clarify this. Thanks!

**Comment by laurentvd** [comment]
Actually, I needed to pass the `id` as a flashvar to make it work. This is also fixed now. Feel free to reopen this issue if things are still unclear.

**Comment by jbeyer05** [comment]
I realized that I could pass as a parameter to the initializer after posting.  But as per your previous post, clarification in the documentation would be great!

Thanks,
Jon
