### ISSUE TITLE
Latest versions of wavesurfer do not seem to work

### ISSUE THREAD

**Issue by dezea** [laurentvd/wavesurfer.swf#7]
I've tried to use the swf version, but I only got the old versions of wavesurfer to work with it. Using the latest ones would resut in a javascript error ("Object.keys: argument is not an Object").
Is there any solution for this?

**Comment by laurentvd** [comment]
Hi @dezea; yeah, you're right, I haven't updated this project in ages. Mostly because I don't have the time to maintain it, but also since it became less relevant. More and more browsers support the JS features wavesurfer.js needs and Flash has become almost extinct. 

Feel free to make a PR if you're able to, but I'd understand if you'll work around it :)

**Comment by dezea** [comment]
Yes, you are right, but until the IE 10-11 versions become really extinct  (I still get some hits from those in my web stats, I've just added a IE check at my website that will document.write the old version of wavesurfer and your swf script.  I will probably remove it altogether in like 1 year since IE usage is down already to only 4% in my recent stats (all IE versions). Anyway, I'll leave my solution here which is pretty straightforward in case someone wanted to use wavesurfer 2 and still load wavesurfer swf with internet explorer:
`
if(/MSIE \d\|Trident.*rv:/.test(navigator.userAgent)) {document.write('<script src="/wavesurfer1.min.js"><\/script><script src="/wavesurfer.swf.js"><\/script><script src="/swfobject.js"><\/script>');}
else {document.write('<script src="/wavesurfer2.min.js"><\/script>')};

PS: Using document.write for stuff like this is not the best solution, but it should not cause [problems](https://developers.google.com/web/updates/2016/08/removing-document-write) as I'm hosting the scripts. I'll probably look into replacing it with jQuery.getScript though for async loading.

**Comment by laurentvd** [comment]
Thanks for posting your workaround here. May be helpful to others. Let's hope that IE 10 & 11 go to their final resting place soon (and Wavesurfer.swf along with them ;-)).
